import os
from datetime import datetime

RUNS_PATH = '../../runs/'
OUTPUT_FORMAT = '.csv'

def creation_time_str():
    """Generate a timestamp string for the current date and time.
    
    Creates a formatted timestamp string using the current local date and time
    in the format YYYYMMDD_HHMMSS. This is commonly used for creating unique
    identifiers or timestamps for files, logs, or other time-sensitive data.
    
    Returns:
        str: A timestamp string in the format 'YYYYMMDD_HHMMSS' representing
            the current local date and time. For example: '20241215_143045'
            for December 15, 2024 at 2:30:45 PM.
    
    Example:
        >>> timestamp = creation_time_str()
        >>> print(timestamp)
        '20241215_143045'
    """
    dt = datetime.now()
    return f'{dt.year}{dt.month:02}{dt.day:02}_{dt.hour:02}{dt.minute:02}{dt.second:02}'

def create_log_file(datetime_str):
    """Create a new CSV log file with timestamp-based filename.
    
    Creates a new log file in the specified runs directory with a filename
    based on the provided datetime string. The file is initialized with
    a CSV header containing 'step,object,count' columns.
    
    Args:
        datetime_str (str): A timestamp string used as the base filename,
            typically in the format 'YYYYMMDD_HHMMSS' as generated by
            creation_time_str().
    
    Returns:
        None: This function creates a file but doesn't return any value.
    
    Note:
        The function relies on global constants RUNS_PATH and OUTPUT_FORMAT
        to determine the full file path. The file is created with UTF-8
        encoding and opened in write mode, overwriting any existing file
        with the same name.
    
    Example:
        >>> timestamp = creation_time_str()
        >>> create_log_file(timestamp)
        # Creates a file like: /path/to/runs/20241215_143045.csv
    """
    path = os.path.join(RUNS_PATH, datetime_str + OUTPUT_FORMAT)
    with open(path, 'w+', encoding='utf-8') as f:
        f.write(f'step,object,count\n')